
SHEETY_ENDPOINT = ''
SHEETY_AUTHORIZATION = ''
FLIGHT_SEARCH_API_KEY = ''
TWILIO_ACCOUNT_SID = ''
TWILIO_AUTH_TOKEN = ''
TWILIO_PH_NO = ''

MY_CITY = ''
MY_PH_NO = ''
MY_EMAIL = ''
MY_PASSWORD = ''
MY_CURRENCY = 'INR'
